services:
  todolist-webapi:
    container_name: todolist.webapi
    image: ${DOCKER_REGISTRY-}todolist.webapi
    build:
      context: .
      dockerfile: /src/TodoList.WebApi/DataAccess
    ports:
      - "3333:80"
      - "4444:443"
    depends_on: 
      - db
  
  db:
    container_name: todolist.db
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER={USERNAME}
      - POSTGRES_PASSWORD={PASSWORD}
      - POSTGRES_DB={DB}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local