networks:
  dev:
    driver: bridge

services:
  todolist-webapi:
    container_name: todolist.webapi
    image: ${DOCKER_REGISTRY-}todolist.webapi
    build:
      context: .
      dockerfile: ./src/TodoList.WebApi/Dockerfile
    ports:
      - '3333:80'
      - '4444:443'
    depends_on:
      - db
      - rabbitmq
    networks: 
      - dev
        
  todolist-emailsender:
    container_name: todolist.emailsender
    image: ${DOCKER_REGISTRY-}todolist.emailsender
    build:
      context: .
      dockerfile: ./src/TodoList.EmailSender/Dockerfile
    ports:
      - '5555:80'
      - '6666:443'
    depends_on:
      - rabbitmq
    networks:
      - dev
  
  db:
    container_name: todolist.db
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER={USERNAME}
      - POSTGRES_PASSWORD={PASSWORD}
      - POSTGRES_DB={DB}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - dev
  
  rabbitmq:
    container_name: todolist.rabbitmq
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER={USERNAME}
      - RABBITMQ_DEFAULT_PASS={PASSWORD}
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - dev

volumes:
  db:
    driver: local